apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    security.opendatahub.io/enable-auth: 'true'
    openshift.io/description: ''
    openshift.io/display-name: qwen3-32b-fp8-dynamic
    serving.kserve.io/deploymentMode: Standard
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    security.opendatahub.io/auth-proxy-type: kube-rbac-proxy
    opendatahub.io/connections: qwen3-32b-fp8-dynamic
    opendatahub.io/model-type: generative
  name: qwen3-32b-fp8-dynamic
  finalizers:
    - odh.inferenceservice.finalizers
    - inferenceservice.finalizers
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--dtype=auto'
        - '--max-model-len=16000'
        - '--gpu-memory-utilization=0.90'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=hermes'
        - '--tensor-parallel-size=1'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '1'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 12Gi
          nvidia.com/gpu: '1'
      runtime: qwen3-32b-fp8-dynamic
      storageUri: 'pvc://qwen3-32b-fp8-dynamic'
    timeout: 30
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
